DROP DATABASE IF EXISTS test;
CREATE DATABASE IF NOT EXISTS test /*!40100 DEFAULT CHARACTER SET utf8 */;
USE test;

DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users (
  id int(11) NOT NULL AUTO_INCREMENT,
  username varchar(50) NOT NULL,
  role varchar(50) NOT NULL,
  password varchar(500) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

